### ISSUE TITLE
Attribute error when starting up the appliation

### ISSUE THREAD

**Issue by allwyn-pradip** [linkedin/iris#633]
The application throws the error when it get started 

/home/iris# tail -f var/log/uwsgi/error.log 
Traceback (most recent call last):
  File "/home/iris/env/lib/python3.8/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/iris/env/lib/python3.8/site-packages/falcon/api.py", line 242, in __call__
    process_resource(req, resp, resource, params)
  File "/home/iris/src/./iris/api.py", line 923, in process_resource
    self.process_admin_acl(req, resource, params)
  File "/home/iris/src/./iris/api.py", line 946, in process_admin_acl
    if req.context.get('app', {}).get('name') in self.allowlisted_apps:
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by diegocepedaw** [comment]
should be addressed by #634
